### ISSUE TITLE
[feature request] user authentication

### ISSUE THREAD

**Issue by pcause** [Pr0dt0s/obsidian-html-server#3]
It would be great to have user authentication.  seems you are using express and they have a sample to do [simple user authentication](https://github.com/expressjs/express/tree/master/examples/auth)

**Comment by Pr0dt0s** [comment]
Hello @pcause, Im glad to see some users of the plugin already.

User Auth seems like a great feature, I'll work on it for the next release, hopefully it will be ready in time for the publishing in the comunity plugins repo.

**Comment by Pr0dt0s** [comment]
Hello @pcause,
Would you mind updating to the latest version and testing the feature out.

**Comment by pcause** [comment]
I installed with BART.  Says it installed, but I don't see it in the community plugins list.  Tried to access a file using localhost and nothing.  On Windows 11.

**Comment by pcause** [comment]
reinstalled and now i get the login page.  enter the user/password.  If I enter a good user/password it just seems to sit and never deliver anything.  I did set a default note but doesn't get there.  After turning on/off a few times and changing default note, couldn't even get login page.  Will restart obsidian and see what happens.

**Comment by pcause** [comment]
also appears that if I change username or password I need to restart the server to have effect.  you might either do automatically or popup a note for the use to do so.

**Comment by Pr0dt0s** [comment]
Hello @pcause, I just released a new minor version that handles some of those things better.

Please feel free to test it out, and let me know of anything.
