### ISSUE TITLE
How do I install the plugin? 

### ISSUE THREAD

**Issue by YousufSSyed** [Pr0dt0s/obsidian-html-server#4]
I tried putting the plugin in the plugins folder and enabling it under Community Plugins, but it said failed to load. I also tried the commands `npm i` and `npm run dev` in the folder and then enabling it but that didn't work either.

**Comment by Pr0dt0s** [comment]
Hello @YousufSSyed,

just copying the files from the latest release inside the folter in the path `./.obsidian/plugins/html-server/` inside your vault folder is all you actually need, the npm commands are just for development purposes.

Let me know if it worked, but if not could you add a bit more information about your current system?

What OS are you using?
What version of Obsidian are you using?

**Comment by YousufSSyed** [comment]
Thanks! I got it working now.
