### ISSUE TITLE
Using metadata in the HTML

### ISSUE THREAD

**Issue by rodrigoportela** [Pr0dt0s/obsidian-html-server#8]
Trying this plugin and seeing the customizable HTML in the settings with some predefined variables, I thought it would be useful in some situations if it was possible to use Obsidian metadata in that HTML template for dynamic variables. For example, to have a `lang` attribute taking the value of a corresponding YAML property in the note being displayed or to add some common elements to the template displaying different content depending on metadata of the current note. Or is this already possible and I'm missing something?

**Comment by Pr0dt0s** [comment]
Hi @rodrigoportela, first of all: thank you for yur feedback!

This sounds like a great feature to have, especially for customization purposes. Im goint to look up into it.

**Comment by Pr0dt0s** [comment]
Hello @rodrigoportela, I just released a new version that should allow all the usecases
